version: '3.8'

services:
  flask-app:
    build:
      context: ./flask-app
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - elas-net

  elasticsearch:
    build:
      context: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - elas-net

networks:
  elas-net:
